### ISSUE TITLE
Measurement Frequency : ID 1446:6a73 X.J.GROUP Stamps.com Model 510 5LB Scale

### ISSUE THREAD

**Issue by alsaibie** [erjiang/usbscale#17]
Hi, 

Just a quick Q. Is there a way to increase the rate at which the scale reports the weight? I'm setting up an experiment and it would be nice to get a faster refresh rate than the few seconds I'm experiencing with this. Can I poll the data instead of an interrupt? Or the scale is just designed that way? 

Are there other scales in the list that do a better job at faster weight refresh?

- Ali

**Comment by sanmai** [comment]
I don't see anything standard in the docs. See for yourself:

 * http://www.usb.org/developers/hidpage/
 * http://www.usb.org/developers/hidpage/pos1_02.pdf (p.29, p.58)

Probably your scale has some undocumented extensions, but that's beyond the scope of this program, as far as I understand.

**Comment by alsaibie** [comment]
I managed to reduce the latency slightly by querying the weight with a small timeout value. Can work with this now. The code for the scale is a big saved, many thanks.
